version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  test:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run Tests
workflows:
  test_app:
    jobs:
      - test
